version: '3.7'

services:
  mongo:
    image: mongo
    hostname: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    command: mongod --bind_ip 0.0.0.0
    restart: always
    networks:
      - payever_app

  rabbitmq:
    image: rabbitmq:3.9.13-management-alpine
    container_name: 'rabbitmq'
    restart: always
    environment:
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_USER: username
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - payever_app

networks:
  payever_app:
    driver: bridge
